// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMBV1a0wF9iUqNQ2JDFm-u2V4w1l3tLQ',
    appId: '1:213737086078:web:bfa56dbd513af84c878c2f',
    messagingSenderId: '213737086078',
    projectId: 'invoicestats',
    authDomain: 'invoicestats.firebaseapp.com',
    storageBucket: 'invoicestats.firebasestorage.app',
    measurementId: 'G-GZ8XY5BEG5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc52S59BbMihNn7NQ9jV2mkJTMRK0G8sg',
    appId: '1:213737086078:ios:60c5004a78ba37be878c2f',
    messagingSenderId: '213737086078',
    projectId: 'invoicestats',
    storageBucket: 'invoicestats.firebasestorage.app',
    iosBundleId: 'com.example.invoicestats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMBV1a0wF9iUqNQ2JDFm-u2V4w1l3tLQ',
    appId: '1:213737086078:web:80963f94d64303f2878c2f',
    messagingSenderId: '213737086078',
    projectId: 'invoicestats',
    authDomain: 'invoicestats.firebaseapp.com',
    storageBucket: 'invoicestats.firebasestorage.app',
    measurementId: 'G-LQQ79ZPDGD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc52S59BbMihNn7NQ9jV2mkJTMRK0G8sg',
    appId: '1:213737086078:ios:60c5004a78ba37be878c2f',
    messagingSenderId: '213737086078',
    projectId: 'invoicestats',
    storageBucket: 'invoicestats.firebasestorage.app',
    iosBundleId: 'com.example.invoicestats',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3d2yNCj0RV4ErUQBC9n4SWWj9gWxFOI',
    appId: '1:213737086078:android:2252d1fa3c1290b6878c2f',
    messagingSenderId: '213737086078',
    projectId: 'invoicestats',
    storageBucket: 'invoicestats.firebasestorage.app',
  );

}